CC=g++
LIBS=-L/data1/workspace/guoxian1/boost_1_49_0/lib
CXXFLAGS=-O2
INCLUDE=-I/data1/workspace/guoxian1/boost_1_49_0/include/
SOURCE=Syslogmodel.cpp 
syslog1: $(SOURCE) 
	$(CC) $(SOURCE) -o $@ $(INCLUDE) $(LIBS) $(CXXFLAGS)
clean:
